version: "3.0"
services:

  server:
    image: cosmtrek/air
    working_dir: /app
    container_name: devcode-backend-todo-challenge-app
    environment:
      APP_ENV: development
    volumes:
      - .:/app