version: '3.0'
services:

  server:
    image: devcode-backend-todo-challenge
    container_name: devcode-backend-todo-challenge-app
    build:
      context: .
      dockerfile: cmd/server/Dockerfile.prod