name: Image Test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs: 
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: make build-docker

    - name: Start docker-compose (DB + App)
      run: make run-prod

    - name: Run Test
      run: make test

    - name: Stop containers
      run: make stop-prod